baseURL = './hugo-course/'
languageCode = 'es'
defaultContentLanguage = "es"
title = 'Coding Empire'
theme = 'hugo-scroll'

# HUGO-SCROLL THEME CONFIG
# This is a "one page"-website, so we do not need these kinds of pages...
disableKinds = ["section", "taxonomy", "term", "RSS", "robotsTXT"]
[params]
    copyright = "© Jane Doe"
    description = "Nutrition Coach & Chef Consultant"
    favicon = "images/favicon.png"
    images = ["images/cover-image.jpg"]
    title = "Jane Doe - Nutrition Coach & Chef Consultant"
    # hidedesignbyline = true
    [params.meta]
        keywords = "some, keywords, for, seo, you, know, google, duckduckgo, and, such"

#menu = 'main'
[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0
