baseURL = 'https://gonzalo-aguero.github.io/hugo-course/'
languageCode = 'es'
title = 'Coding Empire'
theme = 'tale'

#menu = 'main'
[menu]
  [[menu.main]]
	identifier = "contacto"
	name = "Contacto"
	title = "Contacto"
	url = "/contacto/"
	weight = 0
  [[menu.main]]
	identifier = "posts"
	name = "Posts"
	title = "Posts"
	url = "/posts/"
	weight = 0
